### ISSUE TITLE
My wallet and rewards page don't match

### ISSUE THREAD

**Issue by FreeBornAngel** [steemit/steemit.com#600] opened 2016-11-07 22:19 UTC
The rewards page is listing rewards that never made it to my wallet.
https://steemit.com/@freebornangel/author-rewards
https://steemit.com/@freebornangel/transfers
As you can see i'm missing 45 sbd in rewards?

**Comment by TimCliff** [comment] 2016-11-08 03:08
Looking at the author rewards page, it says "Estimated author rewards last week: 47.649 STEEM POWER".
In the wallet it says the user has "STEEM POWER: 33.509 STEEM".
There have been no power downs.
I don't think there is 45 SBD in missing rewards, but there is quite a large discrepancy between these two numbers.

**Comment by tibonova** [comment] 2016-11-08 12:07
Since the "Estimated author rewards last week" is counted by the "Daily average author rewards" x 7, the problem is maybe in the calculation of the latter. 

Is there any possibility for that the resteemed content is counted in somehow?

**Comment by roadscape** [comment] 2016-11-08 17:07
> Since the "Estimated author rewards last week" is counted by the "Daily average author rewards" x 7, the problem is maybe in the calculation of the latter. 

Yes, and this is due to temporally limited information from the backend which results in estimates being based on very few data points. This is related to https://github.com/steemit/steemit.com/issues/375 and should be largely resolved by https://github.com/steemit/steem/issues/521

Until it's resolved we may want to remove all "estimates" and "averages" on the rewards tabs, and just show the raw data.

**Comment by tibonova** [comment] 2016-11-09 14:23
> Until it's resolved we may want to remove all "estimates" and "averages" on the rewards tabs, and just show the raw data.
I second that. No data is better than misleading data which makes confusion and distrust.

**Comment by FreeBornAngel** [comment] 2016-11-09 17:49
Can ya'll point me to these 'very few data points'?
I much prefer the conspiracy answer to the gigo answer and would like to confirm that somebody has not jacked me.
Thanks.

**Comment by roadscape** [comment] 2016-11-09 18:17
@FreeBornAngel - the rows in "AUTHOR REWARDS HISTORY" is the entire set of data which is used to derive the summary above.

This is an open source project, so you can see how the stats are generated here: https://github.com/steemit/steemit.com/blob/develop/app/components/modules/AuthorRewards.jsx

**Comment by FreeBornAngel** [comment] 2016-11-09 18:20
Yes, please forgive me, I'm aware of open source, but greek is still greek even written in front of me.
How can the data set be sooooo far off? Doesn't it just track the garbage coming in?

**Comment by roadscape** [comment] 2016-11-09 18:36
The last reward shown was 2016-11-07T02:38:09.000Z
The first reward shown was 2016-11-07T01:03:48.000Z

The total STEEM POWER rewarded adds up to 0.449
The time difference between first and last reward is 94.35 minutes
There are 1440 minutes in a day

0.449/(94.35/1440) = ~6.8527 STEEM POWER per day

Which is where you get
![image](https://cloud.githubusercontent.com/assets/5168676/20149793/cf0cc446-a680-11e6-89d1-425b16ce8741.png)

Multiply 6.8527 by 7 and you get ~47.9689 STEEM POWER per week:
![image](https://cloud.githubusercontent.com/assets/5168676/20149847/013408ee-a681-11e6-8133-dd2a56ead98c.png)

If we had more reward records to go off of, the averages wouldn't be so badly skewed, which is why I'm suggesting we hide all "estimates" until the API issue is fixed

**Comment by FreeBornAngel** [comment] 2016-11-09 18:50
Grr,...ok, thank you!!

**Closed** 2016-11-09 18:52 UTC

**Comment by roadscape** [comment] 2016-11-09 18:56
I've replaced the existing stats with just a 7-day summary:

![image](https://cloud.githubusercontent.com/assets/5168676/20150475/1b6fb944-a684-11e6-8e4f-46238a571949.png)

This might now underestimate total rewards (again, until API is fixed), but still more useful imo.
