### ISSUE TITLE
Power down minimal amount error mislabeled as transaction broadcast error

### ISSUE THREAD

**Issue by fortaleza** [steemit/steemit.com#815] opened 2016-12-08 11:55 UTC
When attempting to power down an amount which less than 10x of account creation fee, a "Transaction broadcast error" appears which makes the user confused, as it does not explain the real reason of the power down failure.

There needs to be a proper explanation together with the current minimal amount of SP required for the power down.  Ideally, the power down option should be disabled when the requirement is not met, accompanied by an explanation to the user. 

This issue has already been raised [#606](https://github.com/steemit/steemit.com/issues/606) but unfortunately the ticket was closed without being resolved.

**Comment by roadscape** [comment] 2016-12-08 15:41
If this is a dupe of #665 could you please add your suggestions there and close this one? Thanks!

**Closed** 2016-12-12 17:26 UTC
Labels: duplicate
