### ISSUE TITLE
Wrong Image Becomes The Thumbnail

### ISSUE THREAD

**Issue by SteemitFbAdmin** [steemit/steemit.com#16] opened 2016-05-24 20:45 UTC
You can see on this post:
https://steemit.com/steem/@cryptoctopus/zrypi-steemit

That the gorgeous lady at the top is suppose to be the thumbnail but since the latest update, it is to bottom picture that is now the thumbnail.

Screenshot: https://box.everhelper.me/attachment/478510/7443bad0-0bc0-4ca2-acff-4c710bd8a887/343907-yxgysGq2RqEWf98K/screen.png

**Comment by bmann** [comment] 2016-08-15 22:49
Duplicate of #108 -- close this one.

**Comment by roadscape** [comment] 2016-08-17 15:57
I don't think this is strictly a duplicate; they may share code but #108 refers to external thumbnails and this issue refers to Steemit.com thumbnails.

But this is an old issue and may have already been resolved... @SteemitFbAdmin is it still a problem?

**Comment by roadscape** [comment] 2016-08-29 17:38
This may be fixed in 91f268b0d3d7ce8bb25b3cf24b7ecf6873f1e8f8

**Comment by jcalfee** [comment] 2016-08-31 13:14
FB is ignoring postimg.io... I do not see the bottom image anymore though, but we know postimg.io is a problem.  Agreed it is a duplicate of #108 .. https://s32.postimg.io/btivr0zsl/steemchick.png

**Comment by roadscape** [comment] 2016-09-14 21:10
Between the previous commit and ad501c9164ff6221e786928143430b89cb0911c9, this should be resolved. 

Please reopen and link to a recent post exhibiting this issue if it persists.

**Closed by roadscape** 2016-09-14 21:10 UTC
