### ISSUE TITLE
Let users upload their pictures without the need of using 3rd party image hosting sites!

### ISSUE THREAD

**Issue by liondani** [steemit/steemit.com#913] opened 2016-12-27 23:17 UTC
![](https://s28.postimg.org/6l3kwpyn1/upload.jpg)

Make it simple for users to upload their pictures when they are making new posts without the need to go outside steemit to upload them via 3rd party image-hosting sites! Competitors have already an advantage over us! We should make it our first priority to solve this if we really want mass adoption!
eSteem, bussy,akasha already "solved" that, we can do exactly what they do if we don't have something better to introduce right now.

**Comment by TimCliff** [comment] 2016-12-28 01:34
It's being worked on here :)
https://github.com/steemit/steemit.com/issues/396

**Comment by sneak** [comment] 2016-12-31 15:03
Closing as duplicate of #396. :)

**Closed by sneak** 2016-12-31 15:03 UTC
