### ISSUE TITLE
Not showing witnesses i'm voting for

### ISSUE THREAD

**Issue by thecryptodrive** [steemit/steemit.com#453] opened 2016-10-10 12:42 UTC
I just logged out of steemdrive and steemsports accounts which I was using to vote witnesses, now I logged in as thecryptodrive and it doesn't show the witnesses I'm voting for. I'm using Chrome and tried ctrl+R to refresh also.

![image](https://cloud.githubusercontent.com/assets/22358264/19236431/ac3990a2-8ef7-11e6-9928-fcf1cc1c8694.png)

**Comment by roadscape** [comment] 2016-10-14 16:59
Duplicate of #437

**Closed by roadscape** 2016-10-14 16:59 UTC
