### ISSUE TITLE
some links in comments are written as relative when should have url scheme prepended

### ISSUE THREAD

**Issue by sneak** [steemit/steemit.com#152] opened 2016-08-19 15:42 UTC
https://steemit.com/bitcoin/@rogerkver/time-to-end-the-block-size-blockade-by-roger-ver#@singularity87/re-rogerkver-time-to-end-the-block-size-blockade-by-roger-ver-20160819t083357084z

This comment by singularity87 has a link to www.reddit.com/r/btcfork but is linking to 

https://steemit.com/bitcoin/@rogerkver/www.reddit.com/r/btcfork

The href is missing the url scheme at the front.  I assume it's a bug in the linkification code that is detecting a URL missing a scheme and adding the a tag.

**Comment by roadscape** [comment] 2016-08-19 16:29
I thought this might have been linkify config, but it turns out to be a "true" md link: 
```Join us at [www.reddit.com/r/btcfork](www.reddit.com/r/btcfork) to [...]```

We should require a protocol to be specified, but what happens to invalid links?
```[url-without-a-protocol.com](important text)```

We shouldn't throw away the URL (nor the title, unless they match).

**Comment by jcalfee** [comment] 2016-08-19 17:04
I believe you need only to allow `http` or `https`.  An option to fix mostly every case would be to just add a prefix if you need one.  If it startes with `/` you can prefix `https://steemit.com`, if it does not start with `/^http/i` then prefix `https://` ..

**Comment by jcalfee** [comment] 2016-08-19 17:05
You can reject invalid protocols before posting..

**Comment by roadscape** [comment] 2016-08-22 19:15
The issue is now fixed, links without a protocol are prepended with `https://`. Invalid protocols are still left unchanged.

> You can reject invalid protocols before posting..

How to handle invalid links generated from other interfaces?

**Comment by sneak** [comment] 2016-09-14 13:44
I would say just don't wrap them in `<a>`. If they're not `http:` or `https:`, simply don't make them links.

**Comment by roadscape** [comment] 2016-09-14 13:51
Those cases are taken care of, but there's the case of getting a invalid `<a>` link in the user-generated content

**Comment by roadscape** [comment] 2016-11-02 15:49
This issue is resolved, will deal with edge cases as they arise

**Closed by roadscape** 2016-11-02 15:49 UTC
