### ISSUE TITLE
Some topics don't show up in search results

### ISSUE THREAD

**Issue by fortaleza** [steemit/steemit.com#816] opened 2016-12-08 12:09 UTC
Some topics, e.g. "sex" do not show up when searched in "Tags and Topics".
They are not listed on the [explore page](https://steemit.com/tags.html/) either. 

As a result, it's impossible to access them unless the user knows the exact URL.

**Comment by svk31** [comment] 2016-12-08 15:24
Closing as duplicate of #115

**Closed by svk31** 2016-12-08 15:24 UTC
