### ISSUE TITLE
Transaction hangs if not logged in with active key.  Ask for login before trying to send. 

### ISSUE THREAD

**Issue by Xeldal** [steemit/steemit.com#207] opened 2016-08-31 15:25 UTC
If you are logged in with posting key on the wallet page and you try to transfer SBD or STEEM after you've filled out all the fields and click transfer it tries to send the transaction before checking if you are logged in.  Since you're logged in with posting it asks you to login again.  After logging in here with the active key the transfer is infinitely stuck and the only option is to cancel everything and start over, re-filling out the forms for transfer.

Please check for active login sometime before attempting to send the transaction.  It's annoying having to cancel and fill out the form a second time.

both chrome and firefox

**Comment by jcalfee** [comment] 2016-08-31 16:44
Did you try this today?  There was a change yesterday.  I was able to login with my posting WIF key then start the STEEM transfer to myself.  It worked, I used my active WIF key in the "Sign" dialog.

**Comment by Xeldal** [comment] 2016-08-31 17:05
Something has changed since I last tested, but it still does not work.  If I'm logged in with posting key, and I fill in the form and click transfer, I get the login prompt.  After logging in here with active key,  it returns me to the form with "Error: Account not found".  I should now be logged in with active but when I click the transfer button, it again asks me to login.  With the same result over and over. 

The only way I've found to get around it is to cancel the transfer, log out, log back in with active, and start the transfer over from the beginning.

**Comment by roadscape** [comment] 2016-09-22 20:57
Is this still a problem?

**Comment by Xeldal** [comment] 2016-09-23 15:59
Yes.  It's still broken.

**Comment by jcalfee** [comment] 2016-09-23 19:13
It does ask me to login with my active key for each transfer.  However, I never see: "Error: Account not found" .. I can transfer to myself or another account.  I did start by logging in with a posting WIF then I sign with an active WIF.

**Comment by roadscape** [comment] 2016-09-27 18:29
@Xeldal could you check if there are any messages in the console when this happens?

This could be related to #238

**Comment by Xeldal** [comment] 2016-09-28 16:09
**app.226df83….js:14 Decoded memo did not match (memo encryption is unavailable)**(anonymous function) @ app.226df83….js:14t @ app.226df83….js:14i @ app.226df83….js:14e @ app.226df83….js:20_constructComponentWithoutOwner @ app.226df83….js:17_constructComponent @ app.226df83….js:17mountComponent @ app.226df83….js:17mountComponent @ app.226df83….js:4performInitialMount @ app.226df83….js:17mountComponent @ app.226df83….js:17mountComponent @ app.226df83….js:4mountChildren @ app.226df83….js:18_createInitialChildren @ app.226df83….js:17mountComponent @ app.226df83….js:17mountComponent @ app.226df83….js:4performInitialMount @ app.226df83….js:17mountComponent @ app.226df83….js:17mountComponent @ app.226df83….js:4performInitialMount @ app.226df83….js:17mountComponent @ app.226df83….js:17mountComponent @ app.226df83….js:4mountChildren @ app.226df83….js:18_createInitialChildren @ app.226df83….js:17mountComponent @ app.226df83….js:17mountComponent @ app.226df83….js:4performInitialMount @ app.226df83….js:17mountComponent @ app.226df83….js:17mountComponent @ app.226df83….js:4a @ app.226df83….js:11perform @ app.226df83….js:5s @ app.226df83….js:11batchedUpdates @ app.226df83….js:12o @ app.226df83….js:3_renderNewRootComponent @ app.226df83….js:11_renderSubtreeIntoContainer @ app.226df83….js:11renderSubtreeIntoContainer @ app.226df83….js:11_renderOverlay @ app.226df83….js:25componentDidMount @ app.226df83….js:25notifyAll @ app.226df83….js:10close @ app.226df83….js:18closeAll @ app.226df83….js:5perform @ app.226df83….js:5perform @ app.226df83….js:5perform @ app.226df83….js:3S @ app.226df83….js:3closeAll @ app.226df83….js:5perform @ app.226df83….js:5batchedUpdates @ app.226df83….js:12u @ app.226df83….js:3r @ app.226df83….js:8enqueueSetState @ app.226df83….js:8r.setState @ app.226df83….js:8s.handleChange @ app.226df83….js:52c @ app.226df83….js:26(anonymous function) @ app.226df83….js:63dispatch @ app.226df83….js:63(anonymous function) @ app.226df83….js:19(anonymous function) @ app.226df83….js:7
app.226df83….js:5 SteemApi exec 0 get_dynamic_global_properties ( [] )
app.226df83….js:5 SteemApi exec 0 get_dynamic_global_properties ( [] )
app.226df83….js:20 Login	dispatchSubmit
app.226df83….js:5 SteemApi exec 0 get_accounts ( [Array[1]] )
app.226df83….js:5 SteemApi exec 0 get_open_orders ( ["enki"] )
app.226df83….js:5 SteemApi exec 2 get_following ( ["enki", "", "blog", 100] )
app.226df83….js:5 SteemApi exec 2 get_following ( ["enki", "", "ignore", 100] )
**app.226df83….js:19 c: uncaught Error: Account not found(…**)e @ app.226df83….js:19n @ app.226df83….js:19n @ app.226df83….js:19(anonymous function) @ app.226df83….js:19
**app.226df83….js:36 TransactionSage Error: Account not found(…)**(anonymous function) @ app.226df83….js:36i @ app.226df83….js:26(anonymous function) @ app.226df83….js:26t.(anonymous function) @ app.226df83….js:26n @ app.226df83….js:19n @ app.226df83….js:19(anonymous function) @ app.226df83….js:19
app.226df83….js:5 SteemApi exec 0 get_accounts ( [Array[1]] )
app.226df83….js:5 SteemApi exec 0 get_dynamic_global_properties ( [] )


The first error for memo I get on the initial attempt to transfer
the following 2 errors I get on trying to Sign.

**Comment by roadscape** [comment] 2016-11-01 15:54
Still can't reproduce this. This is what I tried:

1. Open an incognito window > navigate to steemit home page > Login
2. Navigate to Wallet page
3. Fill out STEEM transfer form: 1 STEEM, blank memo > Submit
4. Authentication form pops up, log in w/ master password
5. Transfer is successful

I've tried these steps using both master password and posting/active key logins. 
I've also tried them with and without 'Keep me logged in'.

@Xeldal could you try to reproduce these steps? If it works in incognito and not in a normal window, then the issue may be with localStorage.

**Comment by Xeldal** [comment] 2016-11-01 16:21
I followed roughly the same steps.

1. Crome incognito, steemit home page, logged in with /posting key.
2. -same-
3. -same-
4. Authentication popup, logged in with /active key
5. "Error: Account not found"

I don't know what a "master" password is or where it comes from.  As far as I know I don't have one unless its another name for Owner key.   All i have is Owner, Active, Posting, Memo, and Signing.

Same result using Firefox Private window.

**Comment by roadscape** [comment] 2016-11-01 16:47
I am able to reproduce the error when I try to log in as "username**/active**" on the wallet form.

@Xeldal could you try again, without using **/active** after username? It should work just fine without it.

A "master password" is a generated password from which 4 keys are derived: posting,active,owner,memo. That's what you would have if you reset your password using Steemit.com. Advanced users can still set keys individually using CLI or other interfaces.

**Comment by Xeldal** [comment] 2016-11-01 17:58
Sweet. dropping the "/active" worked in all cases.  (Crome, FF, incognito)
Thanks.

**Comment by roadscape** [comment] 2016-12-08 20:35
No reports of this for a while, closing.

**Closed by roadscape** 2016-12-08 20:35 UTC
