### ISSUE TITLE
command-clicking/middle-clicking on usernames in upvoter list popup closes popup

### ISSUE THREAD

**Issue by sneak** [steemit/steemit.com#473] opened 2016-10-12 21:34 UTC
Reproduce: click "x votes" nav at bottom of post to open list of top accounts that upvoted a post.  Middle click a name.

Expected: account list popup stays open, user's profile opens in a new tab.

Actual: account list popup _closes_, user's profile opens in a new tab.

**Comment by roadscape** [comment] 2016-11-17 15:42
Dupe of #641

**Closed by roadscape** 2016-11-17 15:42 UTC
Labels: bug, UI
