### ISSUE TITLE
Possible Follower Count Bug

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steemit.com#799] opened 2016-12-07 14:18 UTC
steemit/steem#671

> As stated I just noticed the number of people I am following is now showing as 61 (instead of 753). If I click on the link it only allows me to view 61 names. I have already had one user asking me why I unfollowed. I am assuming this is a bug? My follower number has not changed. Here is a post I made about this. It seems I am not the only experiencer of this issue:

> https://steemit.com/steemit/@thecryptofiend/possible-bug-over-90-of-people-i-am-following-have-vanished-since-the-fork-down-from-753-to-61

> I thought I should let you all know ASAP. Thanks.

---

> I see the same issue. My profile cycles between 143 and 1034 people followed.
> If I hard refresh my profile page it shows 1034 for a moment, before changing back to 143

**Comment by svk31** [comment] 2016-12-07 14:23
I'm unable to reproduce the issue.

![image](https://cloud.githubusercontent.com/assets/6890015/20971251/bc92cf7e-bc5e-11e6-930a-d11e86531738.png)

**Comment by thecryptofiend** [comment] 2016-12-07 14:39
Thanks - Yes  it only seems to occur when you view your own page - others can see the correct numbers.

**Comment by svk31** [comment] 2016-12-07 16:43
Ok that does help and I can reproduce it by forcing the user. @jcalfee It's caused by the fact that FollowSaga is initiated twice for your own user upon login. You can reproduce it by forcing the current user here: https://github.com/steemit/steemit.com/blob/develop/app/redux/User.js#L73

Just insert this line `payload.username = "thecryptofiend"`

This will be partly fixed by #772 (the count will be correct), but the Map still needs to contain all the followers so this issue needs to be fixed too.

**Comment by thecryptofiend** [comment] 2016-12-07 17:30
@svk31 Thank you for your assistance.  I am clueless when it comes to programming so thank you for explaining it.  I think most of us were worried in case we would not be able to get the followers back!

**Closed** 2016-12-07 23:40 UTC
