### ISSUE TITLE
When clicking a link, force refresh instead of using cache

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#516] opened 2016-10-21 15:53 UTC
I've noticed that when I am browsing the site, a lot of times when I click on "Feed", "Blog", or similar buttons that it just shows a cached version, rather than downloading the latest data. If I manually refresh it loads the newest data. Can it be forced at the site level to reload with fresh data every time the user clicks on a different page?

**Comment by TimCliff** [comment] 2016-10-22 02:45
This may only be an issue on Safari. I will do some more testing to see if it can be reproduced in other browsers.

**Comment by TimCliff** [comment] 2016-11-04 21:26
Could possibly be fixed by https://github.com/steemit/steemit.com/issues/593

**Comment by roadscape** [comment] 2016-12-08 16:15
I believe this is essentially a dupe of #593

**Closed by roadscape** 2016-12-08 16:15 UTC
Labels: bug, UI

**Comment by TimCliff** [comment] 2016-12-08 16:38
@roadscape - this is a different issue. For 593, it is dealing with the scenario where a user is browsing the feed, and clicking 'feed' does not refresh.

This issue is for cases where the user is browsing their feed (for example) and click 'blog' - but the blog page loads cached data instead of refreshing.

593 seems to be a design choice, but this issue is more of an unintended behavior. At least based on what you described in 593 - this one seems like a bug.

**Comment by roadscape** [comment] 2016-12-08 16:52
@TimCliff 

> This issue is for cases where the user is browsing their feed (for example) and click 'blog' - but the blog page loads cached data instead of refreshing.

This could still be caused by the bug noted in 593 **if** Blog was the first page the user loaded.

**Comment by TimCliff** [comment] 2016-12-08 17:07
Ah, ok. Makes sense.
