### ISSUE TITLE
Steemit Upvote Bug! @dailyfeed

### ISSUE THREAD

**Issue by harmeetchuti** [steemit/steemit.com#88] opened 2016-07-30 03:45 UTC
There is a bug/issue for me that affects the payout rewards for old posts that have already been paid out. When up voting my old blog, it gives me a transaction error about not being able to upvote after the post is paid out. And then the payout reward still increases by a few cents!

If this is happening for everyone then they can just keep mashing the upvote button to increase the reward slowly. Could someone look into this an clarify what's actually happening? 

Heres a video I made of the issue.
https://youtu.be/hxbQdhB8zGA

**Comment by harmeetchuti** [comment] 2016-07-30 03:52
https://steemit.com/marijuana/@dailyfeed/super-lemon-haze

I upvoted this blog a few times and the reward went up by a

**Comment by harmeetchuti** [comment] 2016-07-30 03:54
Sorry I'm still getting use to Github. I meant to say that the post went up by a few dollars. So this could be a big issue if everyone can still upvote when they shouldnt be allowed.

**Comment by theoreticalbts** [comment] 2016-08-03 16:03
I encountered this today.  The problem is the UI shows the up arrow greyed out when you've already voted on a post in a past payout cycle.  The backend will prevent you from voting again, but the UI doesn't accurately present the information that you've already voted in this case.

**Comment by roadscape** [comment] 2016-08-10 16:23
This has been fixed in #110.

**Closed by roadscape** 2016-08-10 16:23 UTC
