### ISSUE TITLE
Feature Request: Unread Replies Count

### ISSUE THREAD

**Issue by jedau** [steemit/steemit.com#149] opened 2016-08-19 05:42 UTC
I'm not sure how hard it would be to do, but one problem that I've been discussing with people is the trouble with replies going unnoticed ([post](https://steemit.com/steemit/@jedau/the-problem-with-one-sided-conversations)). One comment by @QuantumAnomaly mentioned the lack of notification for unread replies or posts:

> Browsing through my profile, I finally noticed that there was a whole section devoted to seeing the replies other people had posted on your content. Since I'm used to other sites (and even forums) that flag you with a little number or notifications icon to let you know when people have mentioned you or interacted with your content, I suppose that I has a sort of unconscious state of mind where I thought that since there was no notification icon that no one was really commenting

It could be just a simple tally beside the "Replies" tab, and/or a notification/flag beside a reply to indicate whether it has been read or is still unread.

What do you guys think?

**Comment by aaroncox** [comment] 2016-08-19 07:53
It's a good idea, but I don't think any sort of "read" or "unread" flag exists on these elements. That's going to be the challenging part of developing something like this.

**Comment by jedau** [comment] 2016-08-19 08:51
Right, I was thinking about the same thing when I took a look at the post elements. Perhaps there's some room for it for future improvements? There really is a lot of benefits that can be gotten from this.

**Comment by roadscape** [comment] 2016-09-22 21:06
Closing as duplicate of #72

**Closed by roadscape** 2016-09-22 21:06 UTC
