### ISSUE TITLE
Clicking author's username on article view page does not go to user's profile

### ISSUE THREAD

**Issue by sneak** [steemit/steemit.com#445] opened 2016-10-08 03:27 UTC
<img width="1039" alt="screen shot 2016-10-07 at 23 26 26" src="https://cloud.githubusercontent.com/assets/408977/19210038/8335921e-8ce5-11e6-9cce-a7a21c3c5f05.png">

It's like the one-choice popup box exists simply to mock me for wanting to go to the profile, knowing my intent, yet making me click a second time to get there.

**Comment by roadscape** [comment] 2016-11-17 15:40
Dupe of #642

**Closed by roadscape** 2016-11-17 15:40 UTC
