### ISSUE TITLE
user profile pages report "no such user" while waiting for page to render

### ISSUE THREAD

**Issue by sneak** [steemit/steemit.com#638] opened 2016-11-17 10:10 UTC
related to #632 - when visiting a user profile page for the first time, "No such user." is flashed before the page renders.

**Comment by jcalfee** [comment] 2016-11-18 16:29
I saw `Unknown Account` flash when I visit a profile.  This is probably what you are referring too..

**Comment by roadscape** [comment] 2016-12-02 20:15
Closing as dupe of #380

**Closed by roadscape** 2016-12-02 20:15 UTC
Labels: bug, UI
