### ISSUE TITLE
Feature: Allow Users to Choose Power Down Amount

### ISSUE THREAD

**Issue by finleyexp** [steemit/steemit.com#929] opened 2017-01-01 02:06 UTC
Went to test Power Down option...wanted to see if it was as easy to use as the the transfer features. But, I didn't realize that the moment I put in my pass the whole mess of Steem Power would start vesting. Is it possible to add the option for users to choose the amount they want to power down like with the transfer feature?

**Comment by pfunks** [comment] 2017-01-02 06:45
It's a good idea. Previously discussed here: #766

**Comment by sneak** [comment] 2017-01-03 20:02
Yes, is dupe of #766.  I would like this feature a lot and will see if we can get it scheduled.

**Closed by sneak** 2017-01-03 20:02 UTC
