### ISSUE TITLE
comments missing under a post, loads after refresh

### ISSUE THREAD

**Issue by abitmore** [steemit/steemit.com#204] opened 2016-08-31 00:02 UTC
This is a repost of https://github.com/steemit/steem/issues/332:

> Happened few times while searching for new users introductions.
> Way to reproduce (sometimes):
> - click on some post, scroll down to potential payout time, etc. comments are visible
> - click on a username (show options to FOLLOW or MUTE)
> - click on username again to get to his home page
> - click again on a same post that you were just watching.
> - scroll down and see no comments.
> - reload would show them again
> 
> I noticed that multiple times, semi-randomly. I just tried to reproduce on exact same post/user as a minute before but without success.

**Comment by roadscape** [comment] 2016-09-15 15:26
I've seen this before, but I can't reproduce it now. If someone is able to, please leave the URLs and steps to reproduce.

**Comment by mcifani** [comment] 2016-12-21 18:32
I couldn't replicate as well with the followed instructions above.  Closing issue as it looks resolved.

**Closed by mcifani** 2016-12-21 18:32 UTC
Labels: bug
