### ISSUE TITLE
Modal minimum size (height) issue

### ISSUE THREAD

**Issue by mynameisek** [steemit/steemit.com#775] opened 2016-12-05 18:49 UTC
When a post is very short, the modal should have a minimum height or adapt to the content, otherwise content from the voters list will not display properly 
![image](https://cloud.githubusercontent.com/assets/8390894/20897726/d4537d2a-bb23-11e6-9807-87993fd7acb6.png)

**Comment by roadscape** [comment] 2016-12-05 19:12
Closing as dupe of #762

**Closed by roadscape** 2016-12-05 19:12 UTC
